project:
  type: website
  render:
    - "*.qmd"
    - "*/*.qmd"
    - "disability-guides/*/*.qmd"

website:
  title: "Digital Resource for Disability"
  # author: "APF"
  # date: "11/2/2023"
  page-navigation: true

  navbar:
    left:
      - disability-guides/index.qmd
      - disability-and-society.qmd
      - about.qmd
      
     

  sidebar:
    - id: default
      style: docked
      contents: []

    - id: autism
      contents:
        - disability-guides/autism/about.qmd
        - disability-guides/autism/identification-causes.qmd
        - disability-guides/autism/history.qmd
        - disability-guides/autism/perspectives.qmd
        - disability-guides/autism/diagnosis.qmd
        - disability-guides/autism/next-steps.qmd
        - disability-guides/autism/early-intervention.qmd
        - disability-guides/autism/cures-and-remedies.qmd
        - disability-guides/autism/education.qmd
        - disability-guides/autism/work.qmd
        - disability-guides/autism/adulting.qmd

  # sidebar:
  #   - id: default
  #     style: docked
  #     contents: auto
  #   - id: disability-guides
  #     contents:
  #       - disability-guides/autism.qmd
  #       - disability-guides/blindness.qmd
          

# bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    page-layout: full

  # pdf:
  #   documentclass: scrreprt



