# Disability and Society

## Understanding disability

As people who are dealing with or working with disabilities, we naturally want to learn more about specific disabilities, be it autism, vision impairment, hearing impairment etc. However, it may make sense to step back to try and understand the concept of disability.  

There has been much social and political discourse around the concept of disability in the last few decades. The discourse includes questions like what does ‘disability’ mean and what does it identify, what are its causes and consequences, and what should be an appropriate response to disability at an individual and societal level.  

Much of this debate has focused on removing or reforming the conventional social definitions and attitudes that have defined disability in terms of pathology or a deficit. Such ‘deficit approach’ to disability, based on medical models of impairments with hard notions of pathology, has led to responses that invoke charity and pity at best. More commonly, such approaches have led to stigma, exclusion or marginalisation of persons identified as disabled.  

The response to this has been to move away from the medical models and to take views that consider disability to be wholly socially constructed and the result primarily of social stigma and discrimination. Many activists reject the concept of disability itself as unhelpful, and advocate terms that remove any implication of essential differences that the relevant groups are supposed to carry.  

In this note, and throughout the accompanying resources, we see a balance between these two views. We do not reject the use of disability as a descriptor. For example, we will not reject the use of “Dyslexic” as a descriptor just because it comes from a medical model of the deficiency referring to the inability to read words. However, we do not believe the differences in human abilities themselves define disability. Most of these human abilities lie along a spectrum and it is impossible to identify or assign disability without reference to context and environmental conditions. For example, someone with dyslexia would be more disabled as a newspaper editor and not as disabled as a crane operator. It may be important to emphasize here that we do not use the words ‘disability’ and ‘disabled’ as medical terms.  

Human beings have psycho-social abilities and characteristics that lie along a spectrum. Any atypicality or differences in these individual abilities may diminish the personal and social functioning of the individual. This may be worsened by the social conditions, including the built environment, the structure of opportunities that society presents to various groups or the attitudes, feelings, and actions the individual confronts in the people around.  

When seen this way, ‘disability’ is a status descriptor that attaches to a person and  

+ Identifies that there are limitations in the person’s functioning in the world 

+ locates the limitations in the interaction between the person’s physical or psychological characteristics and the social environment 

+ acknowledges that it may actually or potentially diminish the person’s wellbeing.  

## Social and policy responses 

The Indvidual identified as disabled, or their immediate caregivers might initiate their own responses to adapt to the challenges arising out of the disability. In addition, disability calls for moral responses that include the duty of care and concern that is expected both out of the primary caregivers and the society at large, including policy responses. The notion of care is not meant as a response of pity or compassion. It is the idea of an ethic of care that is part of a broader set of moral considerations, including respect, responsibility, inclusion, and justice.  

Thus, our understanding of disability is an affirmative model in the sense that disability is not automatically assumed to be socially crippling. Similarly, the responses to disability are also assumed to be within the range of diversity that can be accepted, responded to and managed by the society. On the other hand, we do not adopt a view that all disability is necessarily socially constructed, which places the onus of response entirely on social values and systems.  

In summary, the broad set of value orientations that we adopt for designing responses include:  

+ Every person who is suspected to be atypical in their repertoire of capacities should have, if they so wish, access to expert assistance in the evaluation and identification of characteristics that might amount to a disability. This is especially important in the case of marginalised and socio-economically disadvantaged communities.  

+ Once identified, the person and their primary caregivers must have access to advice and support to help understand how the disability might influence or limit the person’s functioning unless actively addressed. In this, we adopt a bio-psycho-social approach to the analysis of disability.  

+ The person must have access to the best expertise that society can currently offer, to ameliorate the impact of the underlying condition that constitutes the disability. Depending on the nature of the disability, responses may range from medical attention to correctable conditions to psychotherapy and at the other end, social and policy accommodations that reduce or eliminate the limitations imposed by the context.  

This view adopts values that do not see disability as natural disadvantage. Disadvantages are largely constituted by social responses. A social orientation that values respect, inclusion, responsibility, and justice will expand the range of disability that can be easily accommodated within normal social life.  

This view also acknowledges that prejudice and ignorance may make social structures and processes less inclusive of disabilities. So systematic attempts to remove stigma and gaps in knowledge that prevent inclusion is a necessary component of possible responses. A long and sustained programme of advocacy that tackles systemic exclusion and leads to more conducive social policy environment is equally important. 


# Bio-psycho-social model of disability

With this understanding of disability, we can see that it puts people living with disabilities on the same equal platform as everyone else, as it should. We can now look at the various aspects of living with disability that we need to account for.  

Do we often see disabilities as deficits to be filled, or diseases that need to be cured? And therefore, do we believe that if we take care of the deficit, then the person will be “normal” and “alright”? Let us say one is visually impaired and is unable to see, and therefore faces certain difficulties. Do we believe that they need to find ways to overcome the specific disabilities that come from their inability to see, and with that, the person will be fine? Or say, if someone has a motor impairment, do we give them a wheelchair or any other way of making sure they can move freely, and that is the solution to it? 

This is one way of looking at disability, as a deficit, as the absence of something they are supposed to have but do not, so let us bridge the gap. This is the biomedical approach, that sees disability as arising primarily from biology, and relies on medical approaches to address the biological difficulties.  

However, this way of looking at it may not present the complete picture. If a person is unable to move around, the biological difficulty needs to be addressed, but how are the others looking at them? Therefore, how does it make them feel? How does this influence how they see themselves? Then again, is the world around them designed to accommodate their difficulty? Or does it amplify their difficulties?  

When we start thinking along these lines, it becomes easy to see that the biomedical model that looks primarily at the biology of the disability, and relies on medical approaches to address the deficits, falls short of dealing with the entirety of disability. This is where the idea of a bio-psycho-social model of disability comes into the picture.  

We need to see disability not just as a product of the biological factors, but also the psychological and social factors. When we say factors, we mean that the biological difficulty or disability may be amplified by the social configurations and societal structure. For example, having ramps around enables a motor impaired person while not having them amplifies their difficulties. Having or not having ramps has nothing to do with the biology of a person, it is about the societal structures around them. Similarly, if a person who is hard of hearing is looked down upon or is thought of as being difficult to deal with, it has psychological and social impact on the person dealing with the disability, as well as the people around them.  

This is what we mean when we say that a disability can be looked at from a broader lens, the bio-psycho-social lens. When we see the biological, as well as the psychological and social implications of it, we can see the range of factors that affect the person living with disability. It can then help us address disability and related issues in a more holistic manner. 

# How should we work with disability?

Let us now look at what we need to keep in mind with respect to interventions for disability. Here, we use the word intervention to mean anything that improves the quality of life for people living with disabilities. Choosing to get a pair of glasses for a person who cannot see well is an intervention, getting a hearing implant for someone with hearing impairment is an intervention, speech therapy is an intervention. What should be the nature of these interventions? How can one choose between various options? Some of what we say here may sound like common sense, but it is important that we be clear about how we make our choices as disabled people, and their parents, teachers, therapists, and social workers.  

The first thing that comes to mind is strengths-based approach. This starts with the presumption of competence - all individuals have the ability to communicate, to participate, to relate to others and to build a meaningful life for themselves, in their own ways. This approach allows us to see the person as a whole, who they truly are, and not limit ourselves to the condition they live with. It allows us to use the strengths of a person to enable their learning and growth.  

The next thing is to see if the interventions are functional for the person. The disabled person is the actor, they are at the centre of the interventions and should have a say in which interventions are working and which are not. The interventions should add to the quality of life of the person with the disability and the people around them. For example, if we have a child with ADHD who runs around and we want him to learn to sit in one place, one must ask if sitting in one place is functional for them. Is it working for them? Does it add to the quality of their life or is the intervention meant to remove the discomfort of the people around? Similarly, people with autism tend to flap their hands as a way of self-regulation. Should we aim to stop it? We should constantly ask if the intervention is aimed at a functional goal for the person.  

Another aspect to see is if the interventions are family centric and consider the community context. We need to recognise people with disabilities live in a social context, with their families, and embedded in the community. So, the interventions need to be something the family understands, approves of, and can execute. The person cannot be forever dependent on some professional who delivers interventions that cannot be handled by anyone else. Therefore, interventions should be designed considering the family circumstances and the social setting of the people with disabilities. For example, if we have a person from the rural community, the goals for that person and the interventions need to be situated in the community where they are growing up, living, and where they aspire to spend their life. 

When we think along these lines, interventions need to be strengths based - they presume competence and use the strengths of the person to make progress. They need to be functional - helpful in improving the quality of life of the person. They need to be situated in the context of the family and community - they account for who the person is, the family and the community they live in and what they aspire to do in that setting. 

# What is inclusion?

