# Preface {.unnumbered}

Persons with Disabilities (PwD) are a hugely underserved population across the world. Despite the tremendous amount of work being done by both the government and non-government actors in the disability space in India, information about various aspects of disabilities is still out of the reach of many people who need it. In many cases, well known and credible sources of information are not India-specific. A lot of such information is not readily usable.

Diversipedia is an attempt to provide India specific information related to the 21 disabilities listed in the Rights of PwD act, 2016. We aspire to provide readily usable information to all the stakeholders in the disability space, including Pwd, their caregivers, agencies working with them et. Here, we cover the various aspects of disability, starting from perspectives on the meaning and implications of disability, to disability specific guides that provide specific information related issues across the lifecycle, to various governmental and non-governmental sources of support. Diversipedia also includes resources to learn more, and provides a directory of service providers and forums where people can interact with each other. 

Please get in touch with abcd@xyz to join this effort. Thank you!